In [1]:
#Code from iamtrask.github.io
import numpy as np

In [28]:
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,0,1,1]]).T

In [4]:
#sigmoid function as the activation func
def nonlin(x, deriv = False):
    if deriv:
        return x*(1-x)
    return 1/(1+np.exp(-x))

In [11]:
np.random.seed(1)
#initialize weights (synapse zero)
syn0 = 2*np.random.random((3,1))-1
print(syn0)

[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [29]:
for j in range(10000):
    l0 = X
    #multiply input data by weights and apply sigmoid func
    l1 = nonlin(np.dot(l0, syn0))
    l1_error = y-l1
    l1_delta = l1_error*nonlin(l1, True)
    syn0 += np.dot(l0.T, l1_delta)
print(l1)
    

[[ 10.04014407]
 [ -9.01094842]
 [ -5.60222331]]
[[  3.67602023e-03]
 [  4.50418951e-07]
 [  9.88317024e-01]
 [  1.02216334e-02]]
